apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-krw-btc-240
  namespace: ttrade
spec:
  selector:
    matchLabels:
      app: kafka-krw-btc-240
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka-krw-btc-240
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kafka-krw-btc-240
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kafka-bit
        image: dogring/tt-kafka-n:1.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: TICK
          value: KRW-BTC
        - name: TOPIC
          value: krw-btc
        - name: RANGE
          value: '240'
        - name: DATA
          value: '60000'
      restartPolicy: Always
