apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  namespace: test
  labels:
    app: test
spec:
  # nodeSelector:
  #   gpu: nvidia
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: test-py
    image: python:3.9-slim
    command:
        - "sh"
        - "-c"
        - |
          pip install pandas
          pip3 install torch --index-url https://download.pytorch.org/whl/cpu
          sleep 604800
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits: 
        cpu: "2"
        memory: "6Gi"
    volumeMounts:
    # - name: config
    #   mountPath: "/etc/config"
      - name: smb
        mountPath: "/source/local_values.py"
        subPath: "ttrade/local_values.py"
        readOnly: true
      - name: azsmb
        mountPath: "/data/raw"
        subPath: "ttrade/raw"
      - name: smb
        mountPath: "/data/data"
        subPath: "ttrade/data/250424"
      - name: smb
        mountPath: "/data/raw2"
        subPath: "ttrade/data/raw"
      - name: smb
        mountPath: "/source/data_transform.py"
        subPath: "ttrade/lib/data_transform.py"
        readOnly: true
      - name: smb
        mountPath: "/source/data_loader.py"
        subPath: "ttrade/lib/data_loader.py"
        readOnly: true
      - name: smb
        mountPath: "/source/indicators.py"
        subPath: "ttrade/lib/indicators.py"
        readOnly: true
      - name: smb
        mountPath: "/src"
        subPath: "pod"
  volumes:
    # - name: datadir
    #   hostPath:
    #     path: /DATA1/ttrade
    #     type: DirectoryOrCreate
    - name: smb
      persistentVolumeClaim:
        claimName: pvc-smb
    - name: azsmb
      persistentVolumeClaim:
        claimName: pvc-azsmb
