apiVersion: batch/v1
kind: Job
metadata:
  name: cpython-0424
  namespace: ttrade
  labels:
    app: cpython
spec:
  template:
    metadata:
      name: cpython
    spec:
      restartPolicy: Never
      containers:
      - name: cpython
        image: dogring/tt-period:0.2
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGET
          value: '5close'
        - name: FUNCTION_NAME
          value: "price_barrier_volat"
        - name: FUNCTION_ARGS
          value: "[120]"
        - name: ARG_TYPES
          value: '["int"]'
        - name: VOLATILITY
          value: "True"
        - name: VOLATILITY_PER
          value: "[0.01,0.02,14]"
        resources:
          requests:
            cpu: "500m"
            memory: "1.5Gi"
          limits: 
            cpu: "1"
            memory: "3Gi"
        volumeMounts:
          - name: smb
            mountPath: "/source/local_values.py"
            subPath: "ttrade/local_values.py"
            readOnly: true
          - name: smb
            mountPath: "/data/raw"
            subPath: "ttrade/data/250424"
            readOnly: true
          - name: smb
            mountPath: "/data/target"
            subPath: "ttrade/data/250424/target"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb