apiVersion: batch/v1
kind: Job
metadata:
  name: data-period-c-0422
  namespace: ttrade
  labels:
    app: data-period-c
spec:
  template:
    metadata:
      name: data-period-c
    spec:
      restartPolicy: Never
      containers:
      - name: data-period-c
        image: dogring/tt-period:0.1
        imagePullPolicy: Always
        env:
        - name: FUNCTION_NAME
          value: "price_barrier"
        - name: FUNCTION_ARGS
          value: "[600, 0.1]"
        - name: ARG_TYPES
          value: '["int", "float"]'
        resources:
          requests:
            cpu: "500m"
            memory: "1.5Gi"
          limits: 
            cpu: "1"
            memory: "3Gi"
        volumeMounts:
          - name: smb
            mountPath: "/source/local_values.py"
            subPath: "ttrade/local_values.py"
            readOnly: true
          - name: smb
            mountPath: "/data/raw"
            subPath: "ttrade/data/250422"
            readOnly: true
          - name: smb
            mountPath: "/data/target"
            subPath: "ttrade/data/250422/target"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb