apiVersion: batch/v1
kind: Job
metadata:
  name: cpython
  namespace: ttrade
  labels:
    app: cpython
spec:
  template:
    metadata:
      name: cpython
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Never
      containers:
      - name: cpython
        image: dogring/tt-period:0.3
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGET
          value: 'close'
        - name: FUNCTION_NAME
          value: "price_barrier_volat"
        - name: FUNCTION_ARGS
          value: "[270]"
        - name: ARG_TYPES
          value: '["int"]'
        - name: VOLATILITY
          value: "True"
        - name: VOLATILITY_PER
          value: "[0.0125,0.02,14]"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits: 
            cpu: "1"
            memory: "6Gi"
        volumeMounts:
          - name: smb
            mountPath: "/source/local_values.py"
            subPath: "ttrade/local_values.py"
            readOnly: true
          - name: smb
            mountPath: "/data/raw"
            subPath: "ttrade/250530/data"
            readOnly: true
          - name: smb
            mountPath: "/data/target"
            subPath: "ttrade/250530/data/target"
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb