apiVersion: v1
kind: Pod
metadata:
  name: trade-btc
  namespace: ttrade
  labels:
    app: trade-btc
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: trade-bit
    image: dogring/tt-trade:1.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
    env:
    - name: MODEL_URL
      value: http://serve-model.ttrade.svc.cluster.local:8080/predictions/mt1
    - name: TOPIC
      value: krw-btc
    - name: TICK
      value: KRW-BTC
    - name: INTERVAL
      value: "30"
    - name: DATA
      value: "10000"
    - name: LARGE
      value: "[240]"
    - name: DATA_N_LENGTH
      value: "{'240': 250}"
    - name: ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: upbit-key
          key: accesskey
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: upbit-key
          key: secretkey
    volumeMounts:
    - name: smb
      mountPath: "/data/data"
      subPath: "ttrade/250530/data"
      readOnly: true
    - name: smb
      mountPath: "/source/local_values.py"
      subPath: "ttrade/local_values.py"
      readOnly: true
    - name: smb
      mountPath: "/source/indicators.py"
      subPath: "ttrade/lib/indicators.py"
      readOnly: true
    - name: smb
      mountPath: "/source/data_transform.py"
      subPath: "ttrade/lib/data_transform.py"
      readOnly: true
  volumes:
  - name: smb
    persistentVolumeClaim:
      claimName: pvc-smb
