apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-krw-btc
  namespace: ttrade
spec:
  selector:
    matchLabels:
      app: kafka-krw-btc
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka-krw-btc
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kafka-krw-btc
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kafka-bit
        image: dogring/tt-kafka:1.7
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: TOPIC
          value: krw-btc
        - name: TICK
          value: KRW-BTC
        - name: INTERVAL
          value: '30'
        - name: ZK_SERVICE
          value: zk-cs.zookeeper.svc:2181
        - name: KAFKA_SERVICE
          value: my-cluster-kafka-bootstrap.kafka.svc:9092
      restartPolicy: Always
