name:
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "train/data_Extract/**"
      - "!train/data_Extract/**.yaml"
      - "!train/data_Extract/**.yml" 
jobs:
  build:
    strategy:
      matrix:

    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was triggered by ${{ github.event_name }}"
      - run: echo "This Job is running on ${{ runner.os }}"
      - run: echo "The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}"

      - name: Checkout source code
        uses: actions/checkout@v4

      - run: ls ${{ github.workspace }}
      - run: echo "Job's status ${{job.status}}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: train/data_Extract
          push: true
          tags: dogring/tt-extract:0.1